on: [push]
jobs:
  buid-and-test:
    run-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - run: npm clean-install
      - run: npm run bluid
      - name: Save cache (ode_modules)
        uses: action/checkout@v4
        with:
          path: |
            node_modules
          key: ${{runner.os}}--node_modules-${{hashFiles('**/package-lock.json')}}

  test:
    run-on: ubuntu-latest
    needs:
      -build
    steps:
      - uses: action/checkout@v4
      - name: Save cache (ode_modules)
        uses: action/checkout@v4
        with:
          path: |
            node_modules
          key: ${{runner.os}}--node_modules-${{hashFiles('**/package-lock.json')}}